export const navlinks = [
	{
		id: 1,
		to: "/",
		name: "HOME",
	},
	{
		id: 2,
		to: "/about",
		name: "ABOUT",
	},
	{
		id: 3,
		to: "/products",
		name: "PRODUCTS",
	},
	{
		id: 4,
		to: "/contact",
		name: "CONTACT",
	},
];

export const testimonials = [
	{
		id: "t1",
		rating: 4,
		author: "Donald Duck",
		imgSrc: "/assets/testimonial-01.png",
		review:
			"Great products and designs and such great quality, they always wash up well no matter how many times I wash them.",
	},
	{
		id: "t2",
		rating: 5,
		author: "Niamh Oxley",
		imgSrc: "/assets/testimonial-02.png",
		review:
			"Beautiful clothes. I always get complements. Good quality and items wash well. products and designs and such great.",
	},
	{
		id: "t3",
		rating: 5,
		author: "Mary Green",
		imgSrc: "/assets/testimonial-03.png",
		review:
			"Great products and designs and such great quality, they always wash up well no matter how many times I wash them.",
	},
];

export const products = [
	{
		id: "pr1",
		rating: "4",
		imgSrc1: "/assets/product-11.jpg",
		imgSrc2: "/assets/product-12.jpg",
		title: "Love Both Engagement Ring",
		categories: ["rings", "bestseller", "featured"],
		brand: "Alexander McQueen",
		price: "119.00",
		priceCrossed: "149.00",
	},
	{
		id: "pr2",
		rating: "4",
		imgSrc1: "/assets/product-21.jpg",
		imgSrc2: "/assets/product-22.jpg",
		title: "Cross of Light Pendant",
		categories: ["necklace", "new arrivals", "featured"],
		brand: "Logitech",
		price: "79.00",
		priceCrossed: "",
	},
	{
		id: "pr3",
		rating: "5",
		imgSrc1: "/assets/product-31.jpg",
		imgSrc2: "/assets/product-32.jpg",
		title: "Circle Signet Ring",
		categories: ["rings", "new arrivals"],
		brand: "Badgley Mischka",
		price: "24.00",
		priceCrossed: "45.00",
	},
	{
		id: "pr4",
		rating: "4",
		imgSrc1: "/assets/product-41.jpg",
		imgSrc2: "/assets/product-42.jpg",
		title: "Reflections Gold Rings",
		categories: ["rings", "bestseller"],
		brand: "Champion",
		price: "36.00",
		priceCrossed: "",
	},
	{
		id: "pr5",
		rating: "5",
		imgSrc1: "/assets/product-51.jpg",
		imgSrc2: "/assets/product-52.jpg",
		title: "Four-Leaf Clover Rings",
		categories: ["rings", "bestseller"],
		brand: "Ballantyne",
		price: "129.00",
		priceCrossed: "149.00",
	},
	{
		id: "pr6",
		rating: "4",
		imgSrc1: "/assets/product-61.jpg",
		imgSrc2: "/assets/product-62.jpg",
		title: "Luxury Rose Pendragon Ring",
		categories: ["rings", "featured"],
		brand: "AllSaints",
		price: "49.00",
		priceCrossed: "59.00",
	},
	{
		id: "pr7",
		rating: "5",
		imgSrc1: "/assets/product-71.jpg",
		imgSrc2: "/assets/product-72.jpg",
		title: "Kalvesna Diamond Twig Ring",
		categories: ["rings", "new arrivals", "featured"],
		brand: "BaubleBar",
		price: "39.00",
		priceCrossed: "59.00",
	},
	{
		id: "pr8",
		rating: "4",
		imgSrc1: "/assets/product-81.jpg",
		imgSrc2: "/assets/product-82.jpg",
		title: "Sparkling Crown Charm Bracelet",
		categories: ["bracelet", "new arrivals"],
		brand: "Desigual",
		price: "124.00",
		priceCrossed: "",
	},
	{
		id: "pr9",
		rating: "5",
		imgSrc1: "/assets/product-91.jpg",
		imgSrc2: "/assets/product-92.jpg",
		title: "Cross Stripes & Stone Bracelet",
		categories: ["bracelet", "bestseller", "featured"],
		brand: "Daniele Fiesoli",
		price: "169.00",
		priceCrossed: "",
	},
	{
		id: "pr10",
		rating: "4",
		imgSrc1: "/assets/product-101.jpg",
		imgSrc2: "/assets/product-102.jpg",
		title: "Echoes Swing word Bracelet",
		categories: ["bracelet", "new arrivals"],
		brand: "Chiara Ferragni",
		price: "79.00",
		priceCrossed: "89.00",
	},
	{
		id: "pr11",
		rating: "4",
		imgSrc1: "/assets/product-111.jpg",
		imgSrc2: "/assets/product-112.jpg",
		title: "Birds of Paradise Pendant",
		categories: ["necklace", "bestseller", "charm & dangle"],
		brand: "Adrianna Papell",
		price: "149.00",
		priceCrossed: "169.00",
	},
	{
		id: "pr12",
		rating: "5",
		imgSrc1: "/assets/product-121.jpg",
		imgSrc2: "/assets/product-122.jpg",
		title: "Echoes Necklace Extension Piece",
		categories: ["necklace", "bestseller", "featured"],
		brand: "Alukas",
		price: "199.00",
		priceCrossed: "",
	},
	{
		id: "pr13",
		rating: "5",
		imgSrc1: "/assets/product-131.jpg",
		imgSrc2: "/assets/product-132.jpg",
		title: "Sterling Silver Dangles Earrings",
		categories: ["earring", "featured"],
		brand: "Alukas",
		price: "139.00",
		priceCrossed: "",
	},
	{
		id: "pr14",
		rating: "4",
		imgSrc1: "/assets/product-141.jpg",
		imgSrc2: "/assets/product-142.jpg",
		title: "Blue Stripes & Stone Earrings",
		categories: ["earring", "featured", "charm & dangle"],
		brand: "Aglini",
		price: "249.00",
		priceCrossed: "260.00",
	},
	{
		id: "pr15",
		rating: "5",
		imgSrc1: "/assets/product-151.jpg",
		imgSrc2: "/assets/product-152.jpg",
		title: "Pandora Flower Stem Earrings",
		categories: ["earring", "bestseller", "charm & dangle"],
		brand: "Dr. Martens",
		price: "119.00",
		priceCrossed: "145.00",
	},
];

export const teams = [
	{
		id: "t1",
		title: "Nimrod Barshad",
		designation: "Founder/CEO",
		imgSrc: "/assets/about-us-team-1.webp",
	},
	{
		id: "t2",
		title: "Claude K. Amadeo",
		designation: "Sales Director",
		imgSrc: "/assets/about-us-team-2.webp",
	},
	{
		id: "t3",
		title: "Luke M. Dugan",
		designation: "Manager",
		imgSrc: "/assets/about-us-team-3.webp",
	},
	{
		id: "t4",
		title: "Mark Pocket",
		designation: "Product Manager",
		imgSrc: "/assets/about-us-team-4.webp",
	},
];

export const clients = [
	{ id: 1, title: "Bershika", imgSrc: "/assets/client-01.png" },
	{ id: 2, title: "H&M", imgSrc: "/assets/client-02.png" },
	{ id: 3, title: "Zara", imgSrc: "/assets/client-03.png" },
	{ id: 4, title: "Mango", imgSrc: "/assets/client-04.png" },
	{ id: 5, title: "Pull&Bear", imgSrc: "/assets/client-05.png" },
];
