export { default as aboutSign } from "../../assets/about-sign.webp";
export { default as aboutUs01 } from "../../assets/about-us-1.webp";
export { default as aboutUs02 } from "../../assets/about-us-2.webp";
export { default as insta01 } from "../../assets/alk_i1.jpg";
export { default as insta02 } from "../../assets/alk_i2.jpg";
export { default as insta03 } from "../../assets/alk_i3.jpg";
export { default as insta04 } from "../../assets/alk_i4.jpg";
export { default as insta05 } from "../../assets/alk_i5.jpg";
export { default as insta06 } from "../../assets/alk_i6.jpg";
export { default as banner01_1024 } from "../../assets/banner-01-1024.jpg";
export { default as banner01_768 } from "../../assets/banner-01-768.jpg";
export { default as banner01 } from "../../assets/banner-01.jpg";
export { default as banner02_1024 } from "../../assets/banner-02-1024.jpg";
export { default as banner02_768 } from "../../assets/banner-02-768.jpg";
export { default as banner02 } from "../../assets/banner-02.jpg";
export { default as banner03_1024 } from "../../assets/banner-03-1024.jpg";
export { default as banner03_768 } from "../../assets/banner-03-768.jpg";
export { default as banner03 } from "../../assets/banner-03.jpg";
export { default as prodDesc01 } from "../../assets/desc-01.png";
export { default as prodDesc02 } from "../../assets/desc-02.png";
export { default as prodDesc03 } from "../../assets/desc-03.png";
export { default as prodDesc04 } from "../../assets/desc-04.png";
export { default as prodDesc05 } from "../../assets/desc-05.png";
export { default as sf_shipping } from "../../assets/free-shipping.jpg";
export { default as logo } from "../../assets/logo-dark.png";
export { default as mbanner01 } from "../../assets/mini-banner-01.webp";
export { default as mbanner02 } from "../../assets/mini-banner-02.jpg";
export { default as aboutMission } from "../../assets/mission.jpg";
export { default as payments } from "../../assets/payments.png";
export { default as sf_returns } from "../../assets/returns.jpg";
export { default as sf_securedPayments } from "../../assets/secured-payment.jpg";
export { default as sf_support } from "../../assets/support.jpg";

export { default as Banner } from "../sections/Banner";
export { default as Categories } from "../sections/Categories";
export { default as Clients } from "../sections/Clients";
export { default as ContactForm } from "../sections/ContactForm";
export { default as FollowUs } from "../sections/FollowUs";
export { default as Footer } from "../sections/Footer";
export { default as Header } from "../sections/Header";
export { default as MiniBanner } from "../sections/MiniBanner";
export { default as OurMission } from "../sections/OurMission";
export { default as OurStory } from "../sections/OurStory";
export { default as OurTeam } from "../sections/OurTeam";
export { default as PagesBanner } from "../sections/PagesBanner";
export { default as SalesFeatures } from "../sections/SalesFeatures";
export { default as SortedProducts } from "../sections/SortedProducts";
export { default as StoreMap } from "../sections/StoreMap";
export { default as StoresNearYou } from "../sections/StoresNearYou";
export { default as Testimonials } from "../sections/Testimonials";

export { default as CategoryDropdown } from "../features/CategoryDropdown";
export { default as CategoryItem } from "../features/CategoryItem";
export { default as Loading } from "../features/Loading";
// export { default as Modal } from "../features/Modal";
export { default as CartSidebar } from "../features/CartSidebar";
export { default as ProductItem } from "../features/ProductItem";
export { default as Ratings } from "../features/Ratings";
export { default as ScrollToTop } from "../features/ScrollToTop";
export { default as SearchBar } from "../features/SearchBar";
export { default as SectionHeading } from "../features/SectionHeading";
export { default as SocialIcons } from "../features/SocialIcons";
export { default as TeamItem } from "../features/TeamItem";
export { default as TestimonialItem } from "../features/TestimonialItem";
export { default as UserCart } from "../features/UserCart";

// export { default as Description } from "../pages/products/Description.tsx";
// export { default as ProductAddCart } from "../pages/products/ProductAddCart.tsx";
// export { default as ProductInfo } from "../pages/products/ProductInfo.tsx";
// export { default as ProductShareNSize } from "../pages/products/ProductShareNSize.tsx";
// export { default as ReturnPolicies } from "../pages/products/ReturnPolicies.tsx";
// export { default as Reviews } from "../pages/products/Reviews.tsx";
// export { default as Shipping } from "../pages/products/Shipping.tsx";

// export { default as ModalQuestions } from "../modals/ModalQuestions.tsx";
// export { default as ModalShare } from "../modals/ModalShare.tsx";
// export { default as ModalSize } from "../modals/ModalSize.tsx";
